language: python
cache: pip
os:
- linux
python:
- '3.6'
sudo: enabled
addons:
  apt:
    packages:
    - mpich
    - libmpich-dev
    - libglib2.0-0
    - libgl1-mesa-glx
    - qt5-default
    - packagekit-gtk3-module
    - libcanberra-gtk-module
install:
- pip install https://github.com/SpikeInterface/spikeextractors/archive/master.zip
- pip install https://github.com/SpikeInterface/spiketoolkit/archive/master.zip
- pip install .
- pip install pytest==4.3
- pip install numpy scipy
- pip install -r requirements_sorters.txt
script: python -m pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: GHlx3HY7vKEIjpQHnoyEDSe1IzFjj0RLebzMkbAvCHWKNUtBCacXY5Ydn/sQHbu2ouAqhPPylKS3/4y0I23654aEPZMLGGEsScUWNZ78UK8/estkF6L/E6GOSqfEJGqbnk1CeH2g3T/1w31G8oDz7C8IJ5RS1WjL8V4M+Vq4EJYVTfqIk1nBowklMalWZHCgpPFCLAAZbnwosJSOC5SbDgNhjKxwIJakh3sYtrbihXELRSpeebm8Gg6JdO2G+f79nz9DZrWIbpW6BTaSoF/4UiQYyq7+DaVgbLPgMVOV8hehtl1EjSIsJA/CITyjHX/N1l/2NcE159i/Hu+F1yleYdN8XKy7M7BuETjiyP1h/j0pgsrUoxXmIXpUICeRrNKfgmJqEGgTh+sPJ9UO5y3GN4f5ivXqtgw/vbDGPqGjAl3FG3OszZgM6bd/kU5KG96YV1HR3FX/6aK3sBDPT82OqwNHz4RmCVF6nPZn8C0dYHIeZzA4PFJbWNwt6WgQg4f20Fi4DCEEPB6W6rJ0hashp7Y9084PUYfRC1RJ5ovuAR5rf5XN7af2e1KUFFSgrybtOD9lGgbXNncBWbV+o++3AUUqfcRo5uJ3uqyzanuBLBiaMnsWYqUR8IIgnccD3rkILNFZM8i+fybrTidfHwqIlnfxnadURJDYnZ6Kl4ohq0Q=
